### ISSUE TITLE
not sure what I'm doing wrong

### ISSUE THREAD

**Issue by alamb91** [Lofter1/anyflip-downloader#12]
I can't seem to download/use the tool, and I've tried every which way I can think of to use it.

**Comment by Lofter1** [comment]
Could you please provide more information? Where do things seem to go wrong? What goes wrong? What have you tried?

**Comment by DrakeGrandX** [comment]
Hi, I seem to have the same problem. Perhaps it's just my lack of familiarity with github or my lack of any tech-savviness (well, programming knowledge to be specific), but I don't seem to be able to locate the file to download. Is it "anyflip-downloader-main.zip" (the one that I can download from the "Code" option)? If so: what's the specific file I need to open from the folder (and do I need any specific program to do so), or does the tool work as an "add-on" to the command prompt and I don't actually have to open anything (just downloading the file is enough)? If not so: the correct file seems to be missing (or at least, isn't showing up to me), alternatively, I'm just looking in the wrong place to download it. Would you be able to be of any help? Many thanks for your work and patience!

**Comment by Lofter1** [comment]
Go to https://github.com/Lofter1/anyflip-downloader/releases/latest, choose the right package for your operating system (Windows, Linux, MacOS/Darwin) and Architecture (ARM Architecture like the newest generation of Apple devices or some Surface devices or the typical AMD64. If in doubt, just use AMD64. Most ARM based systems have a compability layer). Then you just need to unpack the file.

You then can put the executable in your application folder or something similar, then you should be able to open a command line and just type `anyflip-downloader`. Otherwise, navigate to the folder where you put the executable and type `./anyflip-downloader`.
