### ISSUE TITLE
Does not work. How should we put the Link?

### ISSUE THREAD

**Issue by CatarinaMartinsBE** [Lofter1/anyflip-downloader#2]

**Comment by Lofter1** [comment]
Could you please provide further information? Do you get an error message? What URL were you trying to download? How did you provide the URL? 

I think the way it's currently working is pretty straight forward. You go to the book you want to download, copy the URL, and execute anyflip-downloader like `anyflip-downloader <url>`

**Comment by Werkaninchen** [comment]
I had a similar issue with online.anyflip.com urls as they already include the /mobile in the url. 
So the fix is to remove everything in the url path but the first two arguments:

example:
online.anyflip.com/abcde/fghi/mobile/index.html -> online.anyflip.com/abcde/fghi/

I also created a pull request to solve that issue and add an option for extracting the pdf name.
