### ISSUE TITLE
MacOS script error

### ISSUE THREAD

**Issue by fredericklessing** [Lofter1/anyflip-downloader#37]
**Describe the bug**
When running the script, it does not detect a release for darwin
OS: MacOS (darwin)

**To Reproduce**
Run scrip on MacOS Terminal

**Expected behavior**
Installation should work normally

**Additional context**

**Comment by nZex** [comment]
documenting for my own sanity since I did this once already and forgot. 

the install script has a typo. [["$architecture" == "x86_64"]] needs the spaces between the brackets and quotes. So
[[ "$architecture" == "x86_64" ]]
This seems to create a directory instead of an executable. Don't know what thats about, but it did print a download path for the tar.gz into terminal, so I downloaded that and moved it into /usr/local/bin but you can just run it where it is. 
At which point, run it. Let macOS give you a lecture and try to trash it. Head to settings, privacy & security, allow application. 

Then it took me longer than I'd like to admit to realise you need to run the program after using cd to be in the folder you want the file to download into, otherwise it just downloads it into the scripts folder. I was expecting an argument.

**Comment by Lofter1** [comment]
The error in the architecture part of the script has been fixed. Trying the install script on my MacOS machine works fine. If the problem should not have been fixed with this for you, please open the issue up again with more information.
