### ISSUE TITLE
libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by 4sStylZ** [Lofter1/anyflip-downloader#45]
**Describe the bug**
Got  this during execution : 

```
asstylz@Blackbox-2:~/.local/bin$ ./anyflip-downloader https://www.warhammer.com/fr-FR/shop/kill-team-compendium-2021-eng
./anyflip-downloader: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./anyflip-downloader)
./anyflip-downloader: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./anyflip-downloader)
```

OS: Windows running Ubuntu via WSL2

Any idea ? :)

**Comment by Lofter1** [comment]
It seems like your problem is the same as the one described in [here](https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found)
Please try the following on your WSL Ubuntu
```
sudo apt update
sudo apt install libc6
```

However, I also saw that you are using an URL that is not supported. I understand that the name "anyflip" in this programs name can be confusing, but this downloader specifically only works with the "anyflip" website (anyflip.com). While I'm thinking about adding support for additional sites, the Warhammer website will **probably** not be part of the supported websites.
